// Gatmach Yuol Nyuon
// SCT211-0504/2021
#include <GL/glew.h>
#include <GL/freeglut.h>
#include <GL/glut.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <vector>

// Window dimensions
int windowWidth = 800;
int windowHeight = 800;

// Structure to store points
struct Point {
    int x, y;
    Point(int _x, int _y) : x(_x), y(_y) {}
};

// Vector to store parabola points - use a reasonable capacity to avoid reallocation
std::vector<Point> parabolaPoints;

// Helper function for rendering text
void renderText(float x, float y, const char* text) {
    glRasterPos2f(x, y);
    for (int i = 0; text[i] != '\0'; i++) {
        glutBitmapCharacter(GLUT_BITMAP_HELVETICA_10, text[i]);
    }
}

// Draw Axes with labels
void drawAxes() {
    // Draw X and Y axes
    glColor3f(0.0, 0.0, 0.0);
    glLineWidth(2.0);
    glBegin(GL_LINES);
    glVertex2f(-20.0, 0.0);
    glVertex2f(20.0, 0.0);
    glVertex2f(0.0, -20.0);
    glVertex2f(0.0, 20.0);
    glEnd();
    
    // Add axis labels
    renderText(19.5, -0.8, "X");
    renderText(-0.8, 19.5, "Y");
    
    // Draw coordinate numbers
    for (int i = -10; i <= 10; i += 2) {
        if (i == 0) continue;
        
        // X-axis labels
        char buffer[10];
        sprintf(buffer, "%d", i);
        renderText(i, -0.5, buffer);
        
        // Y-axis labels
        renderText(-0.7, i, buffer);
    }
}

// Draw Grid
void drawGrid() {
    glColor3f(0.8, 0.8, 0.8);
    glLineWidth(0.5);
    glBegin(GL_LINES);
    for (int i = -20; i <= 20; i += 1) {
        if (i == 0) continue;
        glVertex2f(i, -20.0);
        glVertex2f(i, 20.0);
        glVertex2f(-20.0, i);
        glVertex2f(20.0, i);
    }
    glEnd();
}

// Function to display equation on screen
void displayEquation() {
    glColor3f(0.0, 0.0, 0.0);
    renderText(-19.5, 19.5, "Parabola: x = y^2  (-10 <= y <= 10)");
    renderText(-19.5, 18.5, "Using Midpoint Algorithm");
}

// Function to trace the midpoint algorithm execution and display the working
void traceAlgorithm() {
    // Trace the first few iterations of the algorithm
    glColor3f(0.0, 0.0, 0.0);
    
    float y = 0;
    float x = 0;
    float d = 0.25; // Initial decision parameter d = 1/2 - (0.5)^2
    
    char buffer[100];
    int lineY = 17;
    
    renderText(-19.5, lineY--, "Midpoint Algorithm Trace:");
    
    // Iteration 1
    sprintf(buffer, "Start at (%0.1f, %0.1f), d = %0.2f", x, y, d);
    renderText(-19.5, lineY--, buffer);
    
    for (int iter = 1; iter <= 5; iter++) {
        if (d > 0) {
            // Choose East (E): x remains the same
            sprintf(buffer, "Iteration %d: d > 0, choose E, keep x = %0.1f", iter, x);
            renderText(-19.5, lineY--, buffer);
            
            d = d - (2*y + 2) + 1;
            y++;
            
            sprintf(buffer, "  New point: (%0.1f, %0.1f), new d = %0.2f", x, y, d);
            renderText(-19.5, lineY--, buffer);
        } else {
            // Choose Northeast (NE): x increases by 1
            sprintf(buffer, "Iteration %d: d <= 0, choose NE, x += 1", iter);
            renderText(-19.5, lineY--, buffer);
            
            d = d - (2*y + 2) + 2;
            x++;
            y++;
            
            sprintf(buffer, "  New point: (%0.1f, %0.1f), new d = %0.2f", x, y, d);
            renderText(-19.5, lineY--, buffer);
        }
    }
}

// Midpoint algorithm for drawing parabola x = y^2
void midpointParabola() {
    // Reserve space to avoid reallocations
    parabolaPoints.clear();
    parabolaPoints.reserve(22); // Enough for y=0 to y=10 and mirrored points
    
    // Starting point is (0,0) - the vertex of the parabola
    int x = 0;
    int y = 0;
    
    // Initial decision parameter
    float d = 0.25; // 1/2 - (0.5)^2 (midpoint between 0 and 1)
    
    // Add the starting point
    parabolaPoints.push_back(Point(x, y));
    
    // Generate points for y from 0 to 10
    while (y < 10) {
        if (d > 0) {
            // Choose East (E): x remains the same
            d = d - (2*y + 2) + 1;
        } else {
            // Choose Northeast (NE): x increases by 1
            x++;
            d = d - (2*y + 2) + 2;
        }
        
        y++;  // Always move up in y
        
        // Add the point
        parabolaPoints.push_back(Point(x, y));
    }
    
    // Print the points calculated by the algorithm
    printf("Points generated by the midpoint algorithm:\n");
    for (const auto& p : parabolaPoints) {
        printf("(%d, %d)\n", p.x, p.y);
    }
}

// Draw the parabola using points calculated by the midpoint algorithm
void drawParabola() {
    // First draw the theoretical parabola curve for reference (light blue)
    glColor3f(0.0, 0.7, 1.0);
    glBegin(GL_LINE_STRIP);
    for (float y = -10.0; y <= 10.0; y += 0.1) {
        float x = y * y;  // x = y^2
        glVertex2f(x, y);
    }
    glEnd();
    
    // Draw the positive y points from the midpoint algorithm (red)
    glColor3f(1.0, 0.0, 0.0);
    glPointSize(5.0);
    glBegin(GL_POINTS);
    for (const auto& p : parabolaPoints) {
        glVertex2f(p.x, p.y);
    }
    glEnd();
    
    // Draw the negative y points using symmetry about x-axis (red)
    glBegin(GL_POINTS);
    for (size_t i = 1; i < parabolaPoints.size(); i++) {
        const Point& p = parabolaPoints[i];
        glVertex2f(p.x, -p.y);
    }
    glEnd();
    
    // Now draw the decision points for visualization
    glColor3f(0.0, 0.5, 0.0);  // Green for decision points
    glPointSize(3.0);
    glBegin(GL_POINTS);
    
    // Only show decision points for the first few iterations
    int x = 0;
    int y = 0;
    float d = 0.25;
    
    for (int i = 0; i < 5 && y < 10; i++) {
        // Plot the midpoint that's being evaluated
        float midY = y + 0.5;
        glVertex2f(x, midY);     // Decision point at (x, y+0.5)
        glVertex2f(x+0.5, midY); // NE option would be around here
        
        if (d > 0) {
            d = d - (2*y + 2) + 1;
        } else {
            x++;
            d = d - (2*y + 2) + 2;
        }
        y++;
    }
    glEnd();
    glPointSize(1.0);
}

void display() {
    glClear(GL_COLOR_BUFFER_BIT);
    
    drawGrid();
    drawAxes();
    drawParabola();
    displayEquation();
    traceAlgorithm();
    
    // Display additional explanation
    glColor3f(0.0, 0.0, 0.0);
    renderText(-19.5, -14.0, "Step-by-step algorithm:");
    renderText(-19.5, -15.0, "1. Start at (0,0) with initial d = 1/2 - (0.5)^2 = 0.25");
    renderText(-19.5, -16.0, "2. If d > 0, choose E (y+1,x); otherwise choose NE (y+1,x+1)");
    renderText(-19.5, -17.0, "3. For E: d_new = d - (2y+2) + 1");
    renderText(-19.5, -18.0, "4. For NE: d_new = d - (2y+2) + 2");
    renderText(-19.5, -19.0, "5. Use symmetry about x-axis for negative y values");
    
    glFlush();
}

void init() {
    glClearColor(1.0, 1.0, 1.0, 1.0); // White background
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluOrtho2D(-20, 20, -20, 20); // Set the coordinate system
    glPointSize(1.0);
}

void reshape(int w, int h) {
    windowWidth = w;
    windowHeight = h;
    glViewport(0, 0, w, h);
}

int main(int argc, char** argv) {
    glutInit(&argc, argv);
    glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
    glutInitWindowSize(windowWidth, windowHeight);
    glutInitWindowPosition(100, 100);
    glutCreateWindow("Parabola x=y^2 using Midpoint Algorithm");
    
    // Calculate the parabola points using midpoint algorithm
    midpointParabola();
    
    init();
    glutDisplayFunc(display);
    glutReshapeFunc(reshape);
    glutMainLoop();
    return 0;
}